services:
  api:
    container_name: realtime-chat-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/usr/src/api
      - ./src/node_modules/:/usr/src/api/node_modules
    networks:
      - app-network
    depends_on:
      - mongo
      - mongo-test
      - redis
      - rabbitmq

  mongo:
    image: mongo:8.0
    container_name: realtime-chat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  mongo-test:
    image: mongo:8.0
    container_name: realtime-chat-mongo-test
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=realtimechat_test_db
    command: mongod --bind_ip_all
    networks:
      - app-network
  
  redis:
    image: redis:7.4.0
    container_name: realtime-chat-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:4-management
    container_name: realtime-chat-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
    driver: local